export const areas = [
  // "Dlf Phase 1 Gurgaon",
  // "Dlf Phase 2 Gurgaon",
  // "Dlf Phase 3",
  // "Dlf Phase 4",
  // "Dlf Phase 5",
  // "DLF Garden City - Sector 89,90,91,92 Gurgaon",
  // "DLF Privana Gurgaon",
  "DLF Aralias Gurgaon",
  "DLF Magnolias Gurgaon",
  "DLF Camellias Gurgaon",
  "Sushant Lok-1 Gurgaon",
  "Sushant Lok-2 Gurgaon",
  "Sushant Lok-3 Gurgaon",
  "South City-1 Gurgaon",
  "South City-2 Gurgaon",
  "Suncity 1 Gurgaon",
  "Suncity 2 Gurgaon",
  "EMAAR Emerald Hills Gurgaon",
  "M3M Golf Estate Gurgaon",
  "M3M Golf Hills Gurgaon",
  "M3M Altitude Gurgaon",
  "Central Park Resorts Gurgaon",
  "Central Park Flower Valley Gurgaon",
  "Paras Quartier Gurgaon",
  "Paras The Manor Gurgaon",
];
